object Versions {
    const val core = "1.7.0"
    const val coreKtx = "1.7.0"
    const val appcompat = "1.6.1"
    const val fragment = "1.6.1"
    const val fragmentKtx = "1.6.1"
    const val material = "1.7.0"
    const val transition = "1.4.1"
    const val viewpager2 = "1.0.0"
    const val recyclerview = "1.2.0"
    const val constraintlayout = "2.1.4"

    const val junit = "4.13.2"
    const val junitVersion = "1.2.0"
    const val testCore = "1.5.0"
    const val espressoCore = "3.6.0"
    const val truth = "1.1.3"
    const val mockk = "1.13.7"
    const val robolectric = "4.10.3"

    const val cxrv = "1.5.4"
    const val insets = "1.2.4"
    const val glide = "4.14.2"
    const val hiddenapibypass = "4.3"

    const val jvmTarget = "1.8"
}

object Libs {
    const val `androidx-core` = "androidx.core:core:${Versions.core}"
    const val `androidx-core-ktx` = "androidx.core:core-ktx:${Versions.coreKtx}"
    const val `androidx-appcompat` = "androidx.appcompat:appcompat:${Versions.appcompat}"
    const val `androidx-fragment` = "androidx.fragment:fragment:${Versions.fragment}"
    const val `androidx-fragment-ktx` = "androidx.fragment:fragment-ktx:${Versions.fragmentKtx}"
    const val `androidx-viewpager2` = "androidx.viewpager2:viewpager2:${Versions.viewpager2}"
    const val `androidx-recyclerview` = "androidx.recyclerview:recyclerview:${Versions.recyclerview}"
    const val `androidx-transition` = "androidx.transition:transition:${Versions.transition}"
    const val `androidx-constraintlayout` = "androidx.constraintlayout:constraintlayout:${Versions.constraintlayout}"
    const val material = "com.google.android.material:material:${Versions.material}"

    const val junit = "junit:junit:${Versions.junit}"
    const val `androidx-test-core` = "androidx.test:core:${Versions.testCore}"
    const val `androidx-junit` = "androidx.test.ext:junit:${Versions.junitVersion}"
    const val `androidx-espresso-core` = "androidx.test.espresso:espresso-core:${Versions.espressoCore}"
    const val truth = "com.google.truth:truth:${Versions.truth}"
    const val mockk = "io.mockk:mockk:${Versions.mockk}"
    const val robolectric = "org.robolectric:robolectric:${Versions.robolectric}"

    const val cxrv = "com.github.xiaocydx.CXRV:cxrv:${Versions.cxrv}"
    const val `cxrv-binding` = "com.github.xiaocydx.CXRV:cxrv-binding:${Versions.cxrv}"
    const val `cxrv-paging` = "com.github.xiaocydx.CXRV:cxrv-paging:${Versions.cxrv}"
    const val `cxrv-viewpager2` = "com.github.xiaocydx.CXRV:cxrv-viewpager2:${Versions.cxrv}"
    const val insets = "com.github.xiaocydx.Insets:insets:${Versions.insets}"
    const val `insets-compat` = "com.github.xiaocydx.Insets:insets-compat:${Versions.insets}"
    const val `insets-systembar` = "com.github.xiaocydx.Insets:insets-systembar:${Versions.insets}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val hiddenapibypass = "org.lsposed.hiddenapibypass:hiddenapibypass:${Versions.hiddenapibypass}"
}